site_name: Steev Docs

nav:
  - ğŸ  Welcome: index.md
  - ğŸ’» Installation: installation.md
  - ğŸ¯ Quick tour: quick-tour.md
  - ğŸ“š Tutorials:
    - âœ”ï¸ Unsloth: tutorials/unsloth.ipynb
  - ğŸ“ Commands:
    - ğŸ”‘ Authentication: command/auth.md
    - ğŸš€ Run: command/run.md
  - ğŸ¤– steev: https://steev.io
  - ğŸ’¬ Discord: https://discord.gg/UxMXBHUWcr
  - Legal:
    - Terms & Conditions: terms.md
    - Privacy Policy: privacy.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black    # Color of headers and navigation
      accent: indigo     # Color of interactive elements
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black    # Color of headers and navigation
      accent: indigo     # Color of interactive elements
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.footnote.tooltips
    - content.code.copy    # Add copy button to code blocks
    - content.code.select  # Add code block selection
    - navigation.footer    # Enable footer navigation

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://steev.io
      name: Home
    - icon: fontawesome/brands/discord
      link: https://discord.gg/UxMXBHUWcr
      name: Discord
  generator: true
  navigation:
    footer:
      - Terms & Conditions: terms.md
      - Privacy Policy: privacy.md
copyright: Copyright &copy; 2024 TBD Labs