site_name: Steev Docs

nav:
  - ğŸ  Welcome: index.md
  - ğŸ’» Installation: installation.md
  - ğŸ¯ Quick tour: quick-tour.md
  - ğŸ“š Tutorials: tutorials.md
  - ğŸ“ Commands:
    - Authentication: command/auth.md
    - Run: command/run.md


theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Dark Mode
    scheme: slate
    toggle:
      icon: material/brightness-4
    primary: indigo
    accent: deep-purple
  features:
    - content.footnote.tooltips

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# welcome.mdë¥¼ í™ˆí˜ì´ì§€ë¡œ ì„¤ì •
